### PR TITLE
If file already exists, use the one and skip overwriting

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by pmjones** [comment]
Ah so!

I think the better fix would be to change this (just above your current fix) ...

``` php
        // look in custom template dir first, then default location
        $dirs = [];
        if ($this->input->tpl) {
            $dirs[] = $this->input->tpl;
        }
        $dirs[] = dirname(dirname(__DIR__)) . DIRECTORY_SEPARATOR . 'templates';
```

... to this:

``` php
        // read default templates first, then override with custom ones if present
        $dirs = [
            dirname(dirname(__DIR__)) . DIRECTORY_SEPARATOR . 'templates'
        ];
        if ($this->input->tpl) {
            $dirs[] = $this->input->tpl;
        }
```

Make sense?

**Comment by harikt** [comment]
That will also work, but do we need to overwrite ?

**Comment by pmjones** [comment]
I think so; if my logic is correct, it reads the default template, then reads the custom one if it exists.

**Comment by harikt** [comment]
yes your logic is correct. But the question was do we need to overwrite to make that possible ? Without that also this would work. But I will make the change according to your suggestion.

**Comment by harikt** [comment]
PR #9 as you suggested.

**Pull request closed without merging**
