### PR TITLE
fix setConn method

### PR DESCRIPTION
**Pull request by shameerc**
setConn should set `$this->input->conn`

### CODE REVIEW

**Comment by pmjones** [comment]
Hm, I was thinking that the command-line option should populate the property, and thereby override the default property value, not that the property should populate the command-line option value. Is it not working as-is?

**Comment by shameerc** [comment]
Not really. Since we are checking for `$this->input->conn` in [places](https://github.com/atlasphp/Atlas.Cli/blob/shameerc/src/Skeleton/Skeleton.php#L199) like [these](https://github.com/atlasphp/Atlas.Cli/blob/shameerc/src/Skeleton/Skeleton.php#L111), it is not working as expected. I think we should be using `$this->conn` instead of `$this->input->conn` and let it override the default value when passed as a command line argument.

**Comment by pmjones** [comment]
Aha! I missed those. Given the intent that the property now supposed to be the "real" connection source, can you change those (and related) uses of $this->input->conn to $this->conn ?

**Comment by shameerc** [comment]
Sure, will send a PR soon.

**Comment by pmjones** [comment]
Thanks!

**Comment by pmjones** [comment]
I just realized that, when creating a table and its template, we need now to check for both $conn (which could have been provided by default) _and_ $table (which may or may not have been passed as a CLI option). Previously, the rules were such that you had to pass both $conn and $table, so checking for one meant the other was there, but that's not the case any more.

I have committed a relevant change in "shameerc". Take a look, try it out, let me know how it works for you.

**Pull request merged**
