### PR TITLE
If file already exists, use the one and skip overwriting

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by pmjones** [comment]
Thanks!

**Comment by harikt** [comment]
I noticed my bad the commit message was copied from old one :P .

**Comment by pmjones** [comment]
That's OK, I'll remember for the change notes. :-)

**Comment by harikt** [comment]
I don't care more for now. It should work with custom template. ie all what I need. There is nothing to look for performance for the current time as it is just a cli to generate things ;) .

**Pull request merged**
